table Product
	lineageTag: dba69bb1-ab01-42ce-9fe0-5b77ac4309a1

	column ProductID
		dataType: int64
		formatString: 0
		lineageTag: 2b285ee7-92a7-4f93-91ac-d700939b64c0
		summarizeBy: none
		sourceColumn: ProductID

		annotation SummarizationSetBy = Automatic

	column ProductName
		dataType: string
		lineageTag: 179d5b93-3c43-46ca-8b5a-f9c44546c985
		summarizeBy: none
		sourceColumn: ProductName

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: c304ff40-248f-4a23-a72a-63057f72ba49
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column UnitPrice
		dataType: int64
		formatString: 0
		lineageTag: 1b6a8032-0628-4e9e-b5b8-e534201e7425
		summarizeBy: none
		sourceColumn: UnitPrice

		annotation SummarizationSetBy = Automatic

	partition Product = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\KavinVishnuN\Downloads\OrderDetails_Data\OrderDetails_Data\Product.csv"),[Delimiter=",", Columns=4, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ProductID", Int64.Type}, {"ProductName", type text}, {"Category", type text}, {"UnitPrice", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

