table Region
	lineageTag: 430610f9-a514-4c17-97cb-e97d2d9982c5

	column RegionID
		dataType: int64
		formatString: 0
		lineageTag: cf32783f-260a-4028-ae89-554d37e6bf88
		summarizeBy: none
		sourceColumn: RegionID

		annotation SummarizationSetBy = Automatic

	column RegionName
		dataType: string
		lineageTag: a38467df-575f-4bee-85a3-1b92df19a96a
		summarizeBy: none
		sourceColumn: RegionName

		annotation SummarizationSetBy = Automatic

	partition Region = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\KavinVishnuN\Downloads\OrderDetails_Data\OrderDetails_Data\Region.csv"),[Delimiter=",", Columns=2, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"RegionID", Int64.Type}, {"RegionName", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

